---
- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: +x
  become: yes

- name: Test kubectl version
  shell: kubectl version --client
  register: kubectl_version

- debug:
    msg: kubectl version {{ kubectl_version.stdout_lines }}