# AWS
region: us-east-1
# Network
vpc_stack_name: SpleenDemoVPCStack-{{ env | title }}
eks_worker_sg: EKSWorkerSG
eks_control_plane_sg: SpleenControlPlaneSG
public_subnet_1: PublicSubnet1
private_subnet_1: PrivateSubnet1
public_subnet_2: PublicSubnet2
private_subnet_2: PrivateSubnet2
# IAM
roles_stack_name: SpleenDemoRolesStack-{{ env | title }}
# EKS
k8s_version: "1.14"
eks_cluster_name: SpleenDemoEKSCluster-{{ env | title }}
eks_cluster_stack_name: SpleenDemoEKSClusterStack-{{ env | title }}
eks_service_role: EKSServiceRoleArn