---
- name: Template conf file
  template:
    src: templates/config.json.j2
    dest: config.json

- name: Upload config file to S3
  aws_s3:
    bucket: "{{ spleen_bucket }}"
    object: "{{ spleen_key }}"
    src: config.json
    mode: put

- name: Delete files
  file:
    path: config.json
    state: absent