---
- name: AWS EKS Node Group
  cloudformation:   
    profile: "{{ profile }}"
    region: "{{ region }}"
    state: "{{ state }}"
    stack_name: "{{ eks_nodegroup_stack_name }}"
    template: roles/eks/templates/eks_nodegroup_cf.yml        
    template_parameters:
      ClusterName: "{{ eks_cluster_stack_name }}-{{ eks_cluster_name }}"
      NodeAutoScalingGroupMaxSize: "{{ eks_nodegroup_max_size }}"
      NodeAutoScalingGroupMinSize: "{{ eks_nodegroup_min_size }}"
      NodeAutoScalingGroupDesiredCapacity: "{{ eks_nodegroup_desired_size }}"
      NodeGroupName: "{{ eks_nodegroup_name }}"
      NodeVolumeSize: "{{ eks_nodegroup_volumme_size }}"
      NodeInstanceType: "{{ eks_nodegroup_instance_type }}"
      Subnet1: "{{ vpc_stack_name }}-{{ private_subnet_1 }}"
      Subnet2: "{{ vpc_stack_name }}-{{ private_subnet_2 }}"
      NodeRoleArn: "{{ iam_stack_name }}-{{ eks_worker_node_role }}"