---
- name: k8s Apply
  block:
  - name: Template files
    template:
      src: "{{ item }}.j2"
      dest: "{{ item }}"
    loop: "{{ files }}"

  - name: Register EKS
    shell: aws eks update-kubeconfig --profile {{ profile }} --name {{ eks_cluster_name }} --region {{ region }}

  - name: Apply configmap
    shell: kubectl apply -f configmap.yml

  - name: Apply deployment
    shell: kubectl apply -f deployment.yml

  - name: Apply service
    shell: kubectl apply -f service.yml

  always:
  - name: Delete files
    file:
      path: "{{ item }}"
      state: absent
    loop: "{{ files }}"