---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Amazon ECR"
Parameters:
  ECRName:
    Type: String
  AWSUSer:
    Type: String
Resources:
  SpleenAppECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - "arn:aws:iam::409153575197:user/gumpdev"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
      Tags: 
        - Key: Name
          Value: !Sub "ECR"